[project]
name = "py"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.14.0"
dependencies = [
    "fastapi[standard]>=0.121.1",
]

[dependency-groups]
dev = [
    "ruff>=0.14.4",
]
